// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VCExample.Models;

namespace VCExample.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20190308201715_DBInitialization")]
    partial class DBInitialization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VCExample.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDone");

                    b.Property<string>("Name");

                    b.Property<int>("Priority");

                    b.HasKey("Id");

                    b.ToTable("ToDo");

                    b.HasData(
                        new { Id = 1, IsDone = true, Name = "TASK_NAME_1", Priority = 1 },
                        new { Id = 2, IsDone = false, Name = "TASK_NAME_2", Priority = 2 },
                        new { Id = 3, IsDone = false, Name = "TASK_NAME_3", Priority = 3 },
                        new { Id = 4, IsDone = true, Name = "TASK_NAME_4", Priority = 4 },
                        new { Id = 5, IsDone = false, Name = "TASK_NAME_5", Priority = 5 },
                        new { Id = 6, IsDone = false, Name = "TASK_NAME_6", Priority = 1 },
                        new { Id = 7, IsDone = true, Name = "TASK_NAME_7", Priority = 2 },
                        new { Id = 8, IsDone = false, Name = "TASK_NAME_8", Priority = 3 },
                        new { Id = 9, IsDone = false, Name = "TASK_NAME_9", Priority = 4 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
